### ISSUE TITLE
Lack of configuration in Readme

### ISSUE THREAD

**Issue by dawidk92** [adityavm/stylelint-at-rule-no-children#1]
Lack of configuration of plugin in Readme.
If I put "stylelint-at-rule-no-children" to plugins array it doesn't work. I have to put "adityavm/stylelint-at-rule-no-children" to "rules" array and it doesn't matter if I pass 'true' or whatever other value to it - it checks for errors anyway

**Comment by adityavm** [comment]
@dawidk92 i thought the enabling / disabling was handled by stylelint, not the plugin . thanks for letting me know!

**Comment by adityavm** [comment]
@dawidk92 investigated it a little further . if you pass `null` to the rule (_not_ `false`, which is not a valid option for rules), like so:

```
...
rules: {
  ...
  "aditayvm/at-rule-no-children": null,
}
```
it disables the plugin .

you can also pass it `["always", { severity: "warning" }]` as usual and it doesn't cause fatal errors . these are options provided by stylelint and has nothing to do with ~~stylelint~~ the plugin

could you confirm whether i understood your issue correctly or not?
