### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by dawidk92** [adityavm/stylelint-at-rule-no-children#2]
Right now plugin is looking for any type of @at-rule. I would like it to check only for:
- @media
- @mixin with specific name (which I use for media queries smth like @include breakpoint(...))

I don't need it to check for @if, @else, @mixins for other purpose than breakpoints, etc.

It would be nice if I could specific this options

**Comment by adityavm** [comment]
@dawidk92 thanks for the suggestion . sounds doable, and i'll look into it .
