### ISSUE TITLE
Always getting `stylelint: Undefined rule adityavm/at-rule-no-children`

### ISSUE THREAD

**Issue by CloudPower97** [adityavm/stylelint-at-rule-no-children#4]
As per the title I do always get `stylelint: Undefined rule adityavm/at-rule-no-children` 

Here is a snippet of the file:

```JSON
{
  "plugins" : ["stylelint-at-rule-no-children"],
  "rules": {
       "adityavm/at-rule-no-children": ["always", { "severity": "warning" }]
  }
}
```

If it makes any difference I've installed this package with `yarn add -D stylelint-at-rule-no-children`

**Comment by adityavm** [comment]
@CloudPower97 can you try changing the `rules: []` declaration to be:

```
rules: [
  ...
  "aditayvm/at-rule-no-children": [{ severity: "warning" }],
]
```

apparently I can't spell my own name sometimes :)

**Comment by CloudPower97** [comment]
Thank you, this fixed the error :+1:

**Comment by exbotanical** [comment]
Will you update the README to reflect this? The typo remains. 
Thanks for the plugin.
